In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split,cross_val_score, GridSearchCV
from sklearn.metrics import plot_confusion_matrix,confusion_matrix
from sklearn.tree import export_text
import joblib

In [2]:
data=pd.read_csv('flag.csv')
data

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,5,1,648,16,10,2,0,3,5,...,0,0,1,0,0,1,0,0,black,green
1,Albania,3,1,29,3,6,6,0,0,3,...,0,0,1,0,0,0,1,0,red,red
2,Algeria,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
3,American-Samoa,6,3,0,0,1,1,0,0,5,...,0,0,0,0,1,1,1,0,blue,red
4,Andorra,3,1,0,0,6,0,3,0,3,...,0,0,0,0,0,0,0,0,blue,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Western-Samoa,6,3,3,0,1,1,0,0,3,...,0,1,5,0,0,0,0,0,blue,red
190,Yugoslavia,3,1,256,22,6,6,0,3,4,...,0,0,1,0,0,0,0,0,blue,red
191,Zaire,4,2,905,28,10,5,0,0,4,...,0,0,0,0,0,1,1,0,green,green
192,Zambia,4,2,753,6,10,5,3,0,4,...,0,0,0,0,0,0,1,0,green,brown
193,Zimbabwe,4,2,391,8,10,5,0,7,5,...,0,0,1,0,1,1,1,0,green,green

In [3]:
data.columns

Index(['name', 'landmass', 'zone', 'area', 'population', 'language',
       'religion', 'bars', 'stripes', 'colours', 'red', 'green', 'blue',
       'gold', 'white', 'black', 'orange', 'mainhue', 'circles', 'crosses',
       'saltires', 'quarters', 'sunstars', 'crescent', 'triangle', 'icon',
       'animate', 'text', 'topleft', 'botright'],
      dtype='object')

In [4]:
data.drop(['landmass', 'zone', 'area', 'population', 'language',
       'religion'],axis=1,inplace=True)
data

,name,bars,stripes,colours,red,green,blue,gold,white,black,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,0,3,5,1,1,0,1,1,1,...,0,0,1,0,0,1,0,0,black,green
1,Albania,0,0,3,1,0,0,1,0,1,...,0,0,1,0,0,0,1,0,red,red
2,Algeria,2,0,3,1,1,0,0,1,0,...,0,0,1,1,0,0,0,0,green,white
3,American-Samoa,0,0,5,1,0,1,1,1,0,...,0,0,0,0,1,1,1,0,blue,red
4,Andorra,3,0,3,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,blue,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Western-Samoa,0,0,3,1,0,1,0,1,0,...,0,1,5,0,0,0,0,0,blue,red
190,Yugoslavia,0,3,4,1,0,1,1,1,0,...,0,0,1,0,0,0,0,0,blue,red
191,Zaire,0,0,4,1,1,0,1,0,0,...,0,0,0,0,0,1,1,0,green,green
192,Zambia,3,0,4,1,1,0,0,0,1,...,0,0,0,0,0,0,1,0,green,brown
193,Zimbabwe,0,7,5,1,1,0,1,1,1,...,0,0,1,0,1,1,1,0,green,green

In [5]:
Target=data['name']
data.drop(['name'],axis=1,inplace=True)
data

,bars,stripes,colours,red,green,blue,gold,white,black,orange,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,0,3,5,1,1,0,1,1,1,0,...,0,0,1,0,0,1,0,0,black,green
1,0,0,3,1,0,0,1,0,1,0,...,0,0,1,0,0,0,1,0,red,red
2,2,0,3,1,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,green,white
3,0,0,5,1,0,1,1,1,0,1,...,0,0,0,0,1,1,1,0,blue,red
4,3,0,3,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,blue,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0,0,3,1,0,1,0,1,0,0,...,0,1,5,0,0,0,0,0,blue,red
190,0,3,4,1,0,1,1,1,0,0,...,0,0,1,0,0,0,0,0,blue,red
191,0,0,4,1,1,0,1,0,0,1,...,0,0,0,0,0,1,1,0,green,green
192,3,0,4,1,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,green,brown
193,0,7,5,1,1,0,1,1,1,0,...,0,0,1,0,1,1,1,0,green,green

In [6]:
data['mainhue'].unique()

array(['green', 'red', 'blue', 'gold', 'white', 'orange', 'black',
       'brown'], dtype=object)

In [7]:
data['botright'].unique()

array(['green', 'red', 'white', 'black', 'blue', 'gold', 'orange',
       'brown'], dtype=object)

In [8]:
data['topleft'].unique()

array(['black', 'red', 'green', 'blue', 'white', 'orange', 'gold'],
      dtype=object)

In [9]:
pd.options.display.max_columns=None
data=pd.get_dummies(data,columns=['mainhue','topleft','botright'])
data

,bars,stripes,colours,red,green,blue,gold,white,black,orange,circles,crosses,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,mainhue_black,mainhue_blue,mainhue_brown,mainhue_gold,mainhue_green,mainhue_orange,mainhue_red,mainhue_white,topleft_black,topleft_blue,topleft_gold,topleft_green,topleft_orange,topleft_red,topleft_white,botright_black,botright_blue,botright_brown,botright_gold,botright_green,botright_orange,botright_red,botright_white
0,0,3,5,1,1,0,1,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,3,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
2,2,0,3,1,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
3,0,0,5,1,0,1,1,1,0,1,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
4,3,0,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0,0,3,1,0,1,0,1,0,0,0,0,0,1,5,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
190,0,3,4,1,0,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
191,0,0,4,1,1,0,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
192,3,0,4,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0
193,0,7,5,1,1,0,1,1,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0

In [10]:
data['text'].unique()[data['text'].unique()>15]

array([], dtype=int64)

In [11]:
d=list(data['circles'].unique())
d.sort()
d

[0, 1, 2, 4]

In [12]:
Model=DecisionTreeClassifier(random_state=42,min_samples_leaf=1,min_samples_split=2)
Model.fit(data,Target)
Model.score(data,Target)

0.9484536082474226

In [13]:
joblib.dump(Model,'Model.pkl')

['Model.pkl']

In [14]:
data.shape

(194, 43)

In [15]:
plt.figure(figsize=(250,250))
plot_tree(Model,rounded=True,filled=True,feature_names=data.columns);
plt.savefig('tree.jpg')